import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/ui/toast/sonner'

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

const outfit = Outfit({
	variable: '--font-outfit',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'SpaceChat',
	description:
		'Generated by create next appSpaceChat is a messenger social media to chat with your friends in the space!!',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} ${outfit.variable} antialiased`}>
				{children}
				<Toaster />
			</body>
		</html>
	)
}
